version: '3'

services:
  app:
   build:
      context: .
   volumes:
    - .:/usr/src/app
   links:
    - mongo
    - postgres
   depends_on:
    - mongo
    - postgres

  mongo:
    image: mongo
    ports:
      - 27017:27017

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      PGDATA: /data/postgres
    ports:
      - 5432:5432

  migration:
    image: app:latest
    command: ["./wait-for-it/wait-for-it.sh", "postgres:5432", "--", "yarn", "migrate"]
    links:
      - postgres
    depends_on:
      - postgres
